name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      releaseVersionName:
        description: new versionName
        required: true

jobs:
  update-version-name:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update versionName
        run: |
          git config --global user.name "[bot] github-actions"
          git config --global user.email "github-actions@example.com"

          echo "${{ github.event.inputs.releaseVersionName }}" > test.txt

          git add -A
          git commit -m "[gh-actions] Update versionName"
          git push
