name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      release_version_name:
        description: new versionName
        required: true

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update versionName
        run: |
          git config --global user.name "[bot] github-actions"
          git config --global user.email "github-actions@example.com"

          echo "${{ github.event.inputs.release_version_name }}" > version.txt

          git add -A
          git commit -m "[gh-actions] Update versionName: ${{ github.event.inputs.release_version_name }}"
          git push

      - name: Create release PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release_test
          base: master
